steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Setup Buildx"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

  - name: "gcr.io/cloud-builders/docker"
    id: "Build and Push"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Prepare tag list
        TAGS="-t us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$SHORT_SHA -t us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$BRANCH_NAME"
        
        # Add latest tag if on main branch
        if [ "$BRANCH_NAME" == "main" ]; then
          TAGS="$$TAGS -t us-docker.pkg.dev/$PROJECT_ID/nebulous/server:latest"
        fi
        
        # Add version tag if TAG_NAME exists
        if [ -n "$TAG_NAME" ]; then
          echo "Detected tag: $TAG_NAME. Adding version tag."
          TAGS="$$TAGS -t us-docker.pkg.dev/$PROJECT_ID/nebulous/server:$TAG_NAME"
        fi
        
        # Build and push all tags in one operation
        docker buildx build \
          --platform linux/amd64 \
          $$TAGS \
          --push \
          .

timeout: "1800s"

options:
  machineType: "E2_HIGHCPU_32"
  env:
    - DOCKER_BUILDKIT=1
