# syntax=docker/dockerfile:1.4

FROM rust:1.86-bullseye

RUN apt-get update && apt-get install -y \
    libssl-dev \
 && rm -rf /var/lib/apt/lists/*

RUN cargo install sccache --locked watchexec-cli

ENV RUSTC_WRAPPER=sccache
ENV SCCACHE_DIR=/sccache

WORKDIR /usr/src/nebulous

CMD ["watchexec", "-w", "src", "-w", "Cargo.toml", "-r", "cargo", "run", "--", "serve", "--host", "0.0.0.0", "--port", "3000"]
